name: website

# Adapted from https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install .
      - run: pip install pdoc
      # ADJUST THIS: build your documentation into pdoc/html/.
      - run: python pdoc/make.py

      - uses: actions/upload-pages-artifact@v1
        with:
          path: pdoc/html/
      
  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
